version: 2
general:
  branches:
    only:
      develop
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv
            pipenv install

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v test/